import Image from "next/image";
import imgThree from "../../../../../assets/1.jpg";
import ScreensSlider from "@/app/_components/ScreensSlider";
import { Metadata } from "next";
import { Button } from "flowbite-react";
import { IProjectData } from "@/app/_components/Portfolio";
const apiUrl = process.env.NEXT_PUBLIC_API_URL;
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const images = [
  { url: "https://i.ibb.co/qCkd9jS/img1.jpg", name: "Switzerland" },
  { url: "https://i.ibb.co/jrRb11q/img2.jpg", name: "Finland" },
  { url: "https://i.ibb.co/NSwVv8D/img3.jpg", name: "Iceland" },
  { url: "https://i.ibb.co/Bq4Q0M8/img4.jpg", name: "Australia" },
  { url: "https://i.ibb.co/jTQfmTq/img5.jpg", name: "Netherland" },
  { url: "https://i.ibb.co/RNkk6L0/img6.jpg", name: "Ireland" },
];

const page = async ({params}:{params:Promise<{projectID:string}>}) => {
  const projectID = await params;
  console.log(projectID.projectID)
  const res = await fetch(`${apiUrl}/api/projects`,{cache:'no-cache'});
  const projects:IProjectData[] = await res.json();
  const project = projects.find((project)=>project._id===projectID.projectID);
  console.log(project)
  return (
    <>
      <div className="container mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-28  mt-[156px] mb-10 border dark:border-gray-800 rounded-[32px] pt-[139px] pe-[111px] pb-[93px] ps-[84px] shadow-lg">
          <div className="flex flex-col gap-10 items-center aspect-[568/478]">
            <Image
              src={imgThree}
              alt="product image"
              className="w-full min-w-[220px] xs:min-w-[260px]  aspect-[568/478] shadow-2xl rounded-[32px] dark:shadow-white/30 "
            ></Image>
            <div className="mt-10 px-10 md:px-0 flex justify-center items-center">
              <ScreensSlider screens={images} />
            </div>
          </div>
          <div className="flex flex-col gap-16">
            <h2 className="leading-[43.57px] uppercase text-responsive1 font-bold dark:text-transparent dark:bg-clip-text  dark:bg-gradient-to-t dark:from-transparent dark:via-white dark:to-transparent after:bg-black">
              {project?.name}
            </h2>
            <p>
               {project?.description}
            </p>
            <div className='flex flex-col sm:flex-row lg:flex-col gap-8'>
              <Button
                href={project?.demo_link}
                target="_blank"
                className="forumBtn px-4 py-1 rounded-3xl lg:!w-full mx-auto sm:mx-0 lg:mx-auto  !shadow-2xl dark:!shadow-white/30"
              >
                <span className="z-[1]">Demo link</span>
                <div className="forumBtn-overlay"></div>
              </Button>
              <Button
                href={project?.purchase_link}
                target="_blank"
                className="forumBtn px-4 py-1 rounded-3xl lg:!w-full mx-auto sm:mx-0 lg:mx-auto !shadow-2xl dark:!shadow-white/30"
              >
                <span className="z-[1]">purchase link</span>
                <div className="forumBtn-overlay"></div>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default page;
