import type { Metadata } from "next";
import "./globals.css";
import "./loader.css";
import ThemeProviderWrapper from "./_components/ThemeProviderWraper";
import MyNavbar from "./_components/MyNavbar";
import { geistMono, geistSans } from "./Fonts";


export const metadata: Metadata = {
  title: "CodeSlu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} darkTheme ` }>
        <ThemeProviderWrapper>
          <MyNavbar />
          <div className="mt-28">
        {children}
        </div>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
