import Image from "next/image";
import img1 from "../../../../../assets/1_New1.jpg";
import { GoDotFill } from "react-icons/go";
import { Metadata } from "next";


const apiUrl = process.env.NEXT_PUBLIC_API_URL;
export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};


const images = {
  url: "https://i.ibb.co/qCkd9jS/img1.jpg",
  name: "Switzerland",
};

export interface IBlogData {
  title: string,
  name: string,
  description: string,
  subject: string,
  image:string,
  date:string,
  _id:string
}

const page = async ({params}:{params:Promise<{blogID:string}>}) => {
  const blogID = await params;
  console.log(blogID.blogID)
  const res = await fetch(`${apiUrl}/api/blog`);
  const blogs:IBlogData[] = await res.json();
  const blog = blogs.find((blog)=>blog._id===blogID.blogID);
  console.log(blog)
  return (
    <div className="container mx-auto">
      <div className="flex flex-col gap-6 w-full bg-gradient-to-b dark:from-[#1b1b1b] dark:via-black dark:to-[#1b1b1b] from-slate-100   via-white to-slate-100 p-4 my-4 rounded-3xl">
        <div className="w-full relative h-[50vh] sm:h-[70vh]">
          <Image src={images.url} alt={images.name} fill={true} className="rounded-t-3xl"></Image>
        </div>
        <div className="flex flex-col gap-5 p-7 ">
          <div className="uppercase flex flex-col sm:flex-row gap-2 items-center">
            <Image
              src={img1}
              alt="blogPoster"
              className="w-[30px] h-[30px] rounded-full"
            ></Image>
            <h4 className="font-semibold">{blog?.name}</h4>
            <GoDotFill />
            <h5 className="text-[#8b96b3] dark:text-[#767b84] ">
              {blog?.date}
            </h5>
            <GoDotFill />
            <h5 className="text-[#8b96b3] dark:text-[#767b84]">{blog?.subject}</h5>
          </div>
          <div className="blog-title">
            {blog?.title}
          </div>
          <p className="mt-4" dangerouslySetInnerHTML={{ __html: blog?.description || "" }}/>
        </div>
      </div>
    </div>
  );
};

export default page;
